### ISSUE TITLE
Problem with fine-grain classification

### ISSUE THREAD

**Issue by lihy-1224** [ttpro1995/TreeLSTMSentiment#8]
In fine-grained mode, dev percentage is more than 80% in my test, but the result in paper is about 50%. I just wonder how to test the fine-grained classification correctly, thx~

**Comment by ttpro1995** [comment]
well, it should like in paper ... :| 
but i haven't focus on fine grained for a while

**Comment by ttpro1995** [comment]
I think you need to fix this 
https://github.com/ttpro1995/TreeLSTMSentiment/issues/3 
and 
https://github.com/ttpro1995/TreeLSTMSentiment/issues/2  (delete all temp data, because you might use binary preprocess data for fine grain) 

please let me know if it work 

by the way, please confirm if binary classification work with result as in paper

**Comment by lihy-1224** [comment]
thanks, I solve it by remove those preprocess data. And binary/fine-grain classification work with result as in original paper
